== To fix the keyboard and the screen flickering

Follow this links also 
. https://wiki.ubuntu.com/Kernel/KernelBootParameters
. https://askubuntu.com/questions/19486/how-do-i-add-a-kernel-boot-parameter

To fix the keyboard and the screen flickering (tested on manjaro 5.13 kernel and ubuntu 21.04)

[frame=ends,sides]
|===
|File Name |Config Name |New Value

|/etc/default/grub
|GRUB_CMDLINE_LINUX_DEFAULT
|GRUB_CMDLINE_LINUX_DEFAULT="i915.enable_psr=0 i8042.direct i8042.dumbkbd"
|===


To fix the keyboard and the screen flickering (tested on manjaro 5.13 kernel and ubuntu 21.04), 
change your grub config entry named GRUB_CMDLINE_LINUX_DEFAULT in /etc/default/grub to:
GRUB_CMDLINE_LINUX_DEFAULT="i915.enable_psr=0 i8042.direct i8042.dumbkbd"
Type sudo update-grub and reboot. +
The first one fixes the flickering, the rest the keyboard. +
You can press e on a distro while installing and add the lines to the installer and start it with ctrl x aswell.

=== To temporarily add a boot parameter to a kernel

Start your system and wait for the GRUB menu to show (if you don't see a GRUB menu, press and hold the left Shift key right after starting the system).
Now highlight the kernel you want to use, and press the e key. You should be able to see and edit the commands associated with the highlighted kernel.
Go down to the line starting with linux and add your parameter foo=bar to its end.
Now press Ctrl + x to boot.

=== To make this change permanent

From a terminal (or after pressing Alt + F2) run:

gksudo gedit /etc/default/grub
(or use sudo nano if gksudo or gedit are not available) and enter your password.
Find the line starting with GRUB_CMDLINE_LINUX_DEFAULT and append foo=bar to its end. For example:

GRUB_CMDLINE_LINUX_DEFAULT="quiet splash foo=bar"
Save the file and close the editor.
Finally, start a terminal and run:

sudo update-grub
to update GRUB's configuration file (you probably need to enter your password).
On the next reboot, the kernel should be started with the boot parameter. To permanently remove it, simply remove the parameter from GRUB_CMDLINE_LINUX_DEFAULT and run sudo update-grub again.

To verify your changes, you can see exactly what parameters your kernel booted with by executing cat /proc/cmdline.
